import { renderPageShell } from '../../views/pageShellView.js';
const refs = [
`[1] Heydari, S., & Mahmoud, Q. H. (2025). Tiny machine learning and on-device inference: A survey of applications, challenges, and future directions. Sensors, 25(10), 3191.`,
`[2] David, R., Duke, J., Jain, A., Janapa Reddi, V., Jeffries, N., Li, J., Kreeger, N., Nappier, I., Natraj, M., Wang, T., Warden, P., & Rhodes, R. (2021). TensorFlow Lite Micro: Embedded machine learning on TinyML systems. Proceedings of Machine Learning and Systems.`,
`[3] Dohi, K., Endo, T., Purohit, H., Tanabe, R., & Kawaguchi, Y. (2021). Flow-based self-supervised density estimation for anomalous sound detection.`,
`[4] Wang, Y., Zheng, Y., Zhang, Y., Xie, Y., Xu, S., Hu, Y., & He, L. (2021). Unsupervised anomalous sound detection for machine condition monitoring using classification-based methods.`,
`[5] Lo, Y.-C., Tsai, T.-L., Yang, C.-W., & Wu, A.-Y. (2024). An efficient anomalous sound detection system for microcontrollers.`,
`[6] Hernández Acosta, L., & Reinhardt, D. (2022). A survey on privacy issues and solutions for voice-controlled digital assistants.`,
`[7] Andriulo, F. C., Fiore, M., Mongiello, M., Traversa, E., & Zizzo, V. (2024). Edge computing and cloud computing for Internet of Things: A review.`,
`[8] González Mendoza, M. A., Gutiérrez, S., Espinosa Loera, R. A., & Ponce, H. (2025). Deploying real-time speech recognition on ESP32 using TinyML and Edge Impulse.`,
`[9] Cioflan, C., Cavigelli, L., & Benini, L. (2024). Boosting keyword spotting through on-device learnable user speech characteristics.`,
`[10] Cioflan, C., Cavigelli, L., Rusci, M., de Prado, M., & Benini, L. (2024). On-Device Domain Learning for Keyword Spotting on Low-Power Extreme Edge Embedded Systems.`,
`[11] Rusci, M., Paci, F., Fariselli, M., Flamand, E., & Tuytelaars, T. (2025). Self-Learning for Personalized Keyword Spotting on Ultralow-Power Audio Sensors.`,
`[12] Lin, J., Zhu, L., Chen, W.-M., Wang, W.-C., Gan, C., & Han, S. (2022). On-Device Training Under 256KB Memory.`,
`[13] Kwon, Y. D., Li, R., Venieris, S. I., Chauhan, J., Lane, N. D., & Mascolo, C. (2024). TinyTrain: Resource-aware task-adaptive sparse training of DNNs at the data-scarce edge.`,
`[14] Pavan, M., Mombelli, G., Sinacori, F., & Roveri, M. (2024). TinySV: Speaker verification in TinyML with on-device learning.`,
`[15] Wilkinghoff, K. (2025). Handling domain shifts for anomalous sound detection.`,
`[16] Dohi, K., Nishida, T., Purohit, H., Tanabe, R., Endo, T., Yamamoto, M., Nikaido, Y., & Kawaguchi, Y. (2022). MIMII DG: Sound dataset for malfunctioning industrial machine investigation and inspection for domain generalization task.`,
`[17] Kfir, T., Tuvyahu, S., Ben Moshe, B., & Anidjar, O. H. (2025). Real-time detection of acoustic anomalies in drone servo motors using edge-based machine learning.`,
`[18] Reis, M. J. C. S. (2025). Lightweight signal processing and edge AI for real-time anomaly detection in IoT sensor networks.`,
`[19] Lo Scudo, F., Pan, Y., & Airaghi, A. (2023). Audio-based anomaly detection on edge devices via self-supervision and spectral analysis.`,
`[20] Nejjar, I., Meunier-Pion, J., Frusque, G., & Fink, O. (2022). DG-Mix: Domain generalization for anomalous sound detection based on self-supervised learning.`,
`[21] Dohi, K., Nishida, T., Purohit, H., Tanabe, R., Endo, T., Nikaido, Y., & Kawaguchi, Y. (2023). Description and discussion on DCASE 2023 challenge task 2: First-shot unsupervised anomalous sound detection for machine condition monitoring.`,
`[22] Nishida, T., Dohi, K., Purohit, H., Tanabe, R., Endo, T., Nikaido, Y., & Kawaguchi, Y. (2024). Description and discussion on DCASE 2024 challenge task 2: First-shot unsupervised anomalous sound detection for machine condition monitoring.`,
`[23] Nishida, T., Dohi, K., Purohit, H., Tanabe, R., Endo, T., Nikaido, Y., & Kawaguchi, Y. (2025). Description and discussion on DCASE 2025 challenge task 2: First-shot unsupervised anomalous sound detection for machine condition monitoring.`,
`[24] Lourenço, A., Rodrigo, J., Gama, J., & Marreiros, G. (2025). On-device edge learning for IoT data streams: A survey.`,
`[25] Purohit, H., Tanabe, R., Ichige, K., Endo, T., Nikaido, Y., Suefusa, K., & Kawaguchi, Y. (2019). MIMII dataset: Sound dataset for malfunctioning industrial machine investigation and inspection.`,
`[26] Koizumi, Y., Saito, S., Uematsu, H., Harada, N., & Imoto, K. (2019). ToyADMOS: A dataset of miniature-machine operating sounds for anomalous sound detection.`,
`[27] Koizumi, Y., Kawaguchi, Y., Imoto, K., Nakamura, T., Nikaido, Y., Tanabe, R., Purohit, H., Suefusa, K., Endo, T., Yasuda, M., & Harada, N. (2020). Description and discussion on DCASE2020 challenge task2: Unsupervised anomalous sound detection for machine condition monitoring.`,
`[28] Kawaguchi, Y., Imoto, K., Koizumi, Y., Harada, N., Niizumi, D., Dohi, K., Tanabe, R., Purohit, H., & Endo, T. (2021). Description and discussion on DCASE 2021 challenge task 2: Unsupervised anomalous sound detection for machine condition monitoring under domain shifted conditions.`,
`[29] Abreha, H. G., Hayajneh, M., & Serhani, M. A. (2022). Federated learning in edge computing: A systematic survey.`,
`[30] Mahdi, O. A., Pardede, E., Bevinakoppa, S., & Ali, N. M. (2025). Federated learning under concept drift: A systematic survey of foundations, innovations, and future research directions.`,
`[31] Hard, A., Partridge, K., Chen, N., Augenstein, S., Shah, A., Park, H. J., Park, A., Ng, S., Nguyen, J., Lopez Moreno, I., Mathews, R., & Beaufays, F. (2022). Production federated keyword spotting via distillation, filtering, and joint federated-centralized training.`,
`[32] Zhang, T., Feng, T., Alam, S., Lee, S., Zhang, M., Narayanan, S. S., & Avestimehr, S. (2023). FedAudio: A federated learning benchmark for audio tasks.`
];
export function render(){ return renderPageShell({title:'References',lead:'Research references used in the proposal context.',body:`<section class='panel'><ol class='ref-list'>${refs.map(r=>`<li>${r}</li>`).join('')}</ol></section>`}); }
